/*******************************************************************************
 * Copyright (c) 2010 - 2012 ACIN, Profactor GmbH
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *   Michael Hofmann, Alois Zoitl, Ingo Hegny
 *     - initial API and implementation and/or initial documentation
 *******************************************************************************/

//!!!autogenerated code - DO NOT EDIT!!!
#include "stringlist.h"

extern const CStringDictionary::TStringId g_nStringIdADDRESS = 0;
extern const CStringDictionary::TStringId g_nStringIdAGENT_GATE = 8;
extern const CStringDictionary::TStringId g_nStringIdANY = 19;
extern const CStringDictionary::TStringId g_nStringIdANY_ADAPTER = 23;
extern const CStringDictionary::TStringId g_nStringIdANY_BIT = 35;
extern const CStringDictionary::TStringId g_nStringIdANY_ELEMENTARY = 43;
extern const CStringDictionary::TStringId g_nStringIdANY_INT = 58;
extern const CStringDictionary::TStringId g_nStringIdANY_MAGNITUDE = 66;
extern const CStringDictionary::TStringId g_nStringIdANY_NUM = 80;
extern const CStringDictionary::TStringId g_nStringIdANY_REAL = 88;
extern const CStringDictionary::TStringId g_nStringIdANY_STRING = 97;
extern const CStringDictionary::TStringId g_nStringIdARRAY = 108;
extern const CStringDictionary::TStringId g_nStringIdARTimeOut = 114;
extern const CStringDictionary::TStringId g_nStringIdATimeOut = 124;
extern const CStringDictionary::TStringId g_nStringIdBOOL = 133;
extern const CStringDictionary::TStringId g_nStringIdBYTE = 138;
extern const CStringDictionary::TStringId g_nStringIdCB_RESET = 143;
extern const CStringDictionary::TStringId g_nStringIdCB_TRIP = 152;
extern const CStringDictionary::TStringId g_nStringIdCD = 160;
extern const CStringDictionary::TStringId g_nStringIdCDO = 163;
extern const CStringDictionary::TStringId g_nStringIdCLEAR = 167;
extern const CStringDictionary::TStringId g_nStringIdCLK = 173;
extern const CStringDictionary::TStringId g_nStringIdCNF = 177;
extern const CStringDictionary::TStringId g_nStringIdCO = 181;
extern const CStringDictionary::TStringId g_nStringIdCOLD = 184;
extern const CStringDictionary::TStringId g_nStringIdCU = 189;
extern const CStringDictionary::TStringId g_nStringIdCUO = 192;
extern const CStringDictionary::TStringId g_nStringIdCURRENT_A_TO_D = 196;
extern const CStringDictionary::TStringId g_nStringIdCV = 211;
extern const CStringDictionary::TStringId g_nStringIdD = 214;
extern const CStringDictionary::TStringId g_nStringIdDATA_IN = 216;
extern const CStringDictionary::TStringId g_nStringIdDATA_IN_BOOL = 224;
extern const CStringDictionary::TStringId g_nStringIdDATA_IN_INT = 237;
extern const CStringDictionary::TStringId g_nStringIdDATA_IN_LINT = 249;
extern const CStringDictionary::TStringId g_nStringIdDATA_IN_LREAL = 262;
extern const CStringDictionary::TStringId g_nStringIdDATA_IN_REAL = 276;
extern const CStringDictionary::TStringId g_nStringIdDATA_IN_STRING = 289;
extern const CStringDictionary::TStringId g_nStringIdDATA_IN_WSTRING = 304;
extern const CStringDictionary::TStringId g_nStringIdDATA_OUT = 320;
extern const CStringDictionary::TStringId g_nStringIdDATA_OUT_BOOL = 329;
extern const CStringDictionary::TStringId g_nStringIdDATA_OUT_INT = 343;
extern const CStringDictionary::TStringId g_nStringIdDATA_OUT_LINT = 356;
extern const CStringDictionary::TStringId g_nStringIdDATA_OUT_LREAL = 370;
extern const CStringDictionary::TStringId g_nStringIdDATA_OUT_REAL = 385;
extern const CStringDictionary::TStringId g_nStringIdDATA_OUT_STRING = 399;
extern const CStringDictionary::TStringId g_nStringIdDATA_OUT_WSTRING = 415;
extern const CStringDictionary::TStringId g_nStringIdDATA_TYPE = 432;
extern const CStringDictionary::TStringId g_nStringIdDATE = 442;
extern const CStringDictionary::TStringId g_nStringIdDATE_AND_TIME = 447;
extern const CStringDictionary::TStringId g_nStringIdDEV_MGR = 461;
extern const CStringDictionary::TStringId g_nStringIdDINT = 469;
extern const CStringDictionary::TStringId g_nStringIdDLY = 474;
extern const CStringDictionary::TStringId g_nStringIdDP = 478;
extern const CStringDictionary::TStringId g_nStringIdDST = 481;
extern const CStringDictionary::TStringId g_nStringIdDT = 485;
extern const CStringDictionary::TStringId g_nStringIdDWORD = 488;
extern const CStringDictionary::TStringId g_nStringIdEI = 494;
extern const CStringDictionary::TStringId g_nStringIdEI0 = 497;
extern const CStringDictionary::TStringId g_nStringIdEI1 = 501;
extern const CStringDictionary::TStringId g_nStringIdEI2 = 505;
extern const CStringDictionary::TStringId g_nStringIdEMB_RES = 509;
extern const CStringDictionary::TStringId g_nStringIdEO = 517;
extern const CStringDictionary::TStringId g_nStringIdEO0 = 520;
extern const CStringDictionary::TStringId g_nStringIdEO1 = 524;
extern const CStringDictionary::TStringId g_nStringIdEO2 = 528;
extern const CStringDictionary::TStringId g_nStringIdEO3 = 532;
extern const CStringDictionary::TStringId g_nStringIdE_CTD = 536;
extern const CStringDictionary::TStringId g_nStringIdE_CTU = 542;
extern const CStringDictionary::TStringId g_nStringIdE_CTUD = 548;
extern const CStringDictionary::TStringId g_nStringIdE_CYCLE = 555;
extern const CStringDictionary::TStringId g_nStringIdE_DELAY = 563;
extern const CStringDictionary::TStringId g_nStringIdE_DEMUX = 571;
extern const CStringDictionary::TStringId g_nStringIdE_D_FF = 579;
extern const CStringDictionary::TStringId g_nStringIdE_F_TRIG = 586;
extern const CStringDictionary::TStringId g_nStringIdE_MERGE = 595;
extern const CStringDictionary::TStringId g_nStringIdE_PERMIT = 603;
extern const CStringDictionary::TStringId g_nStringIdE_RDELAY = 612;
extern const CStringDictionary::TStringId g_nStringIdE_REND = 621;
extern const CStringDictionary::TStringId g_nStringIdE_RESTART = 628;
extern const CStringDictionary::TStringId g_nStringIdE_RS = 638;
extern const CStringDictionary::TStringId g_nStringIdE_RTimeOut = 643;
extern const CStringDictionary::TStringId g_nStringIdE_R_TRIG = 654;
extern const CStringDictionary::TStringId g_nStringIdE_SELECT = 663;
extern const CStringDictionary::TStringId g_nStringIdE_SPLIT = 672;
extern const CStringDictionary::TStringId g_nStringIdE_SR = 680;
extern const CStringDictionary::TStringId g_nStringIdE_SWITCH = 685;
extern const CStringDictionary::TStringId g_nStringIdE_TimeOut = 694;
extern const CStringDictionary::TStringId g_nStringIdG = 704;
extern const CStringDictionary::TStringId g_nStringIdGEN_CLIENT = 706;
extern const CStringDictionary::TStringId g_nStringIdGEN_E_DEMUX = 717;
extern const CStringDictionary::TStringId g_nStringIdGEN_E_MUX = 729;
extern const CStringDictionary::TStringId g_nStringIdGEN_PUBL = 739;
extern const CStringDictionary::TStringId g_nStringIdGEN_PUBLISH = 748;
extern const CStringDictionary::TStringId g_nStringIdGEN_SERVER = 760;
extern const CStringDictionary::TStringId g_nStringIdGEN_SUBL = 771;
extern const CStringDictionary::TStringId g_nStringIdGEN_SUBSCRIBE = 780;
extern const CStringDictionary::TStringId g_nStringIdID = 794;
extern const CStringDictionary::TStringId g_nStringIdIED50_51 = 797;
extern const CStringDictionary::TStringId g_nStringIdIED64 = 806;
extern const CStringDictionary::TStringId g_nStringIdIN = 812;
extern const CStringDictionary::TStringId g_nStringIdIND = 815;
extern const CStringDictionary::TStringId g_nStringIdINIT = 819;
extern const CStringDictionary::TStringId g_nStringIdINITO = 824;
extern const CStringDictionary::TStringId g_nStringIdINST_ID = 830;
extern const CStringDictionary::TStringId g_nStringIdINT = 838;
extern const CStringDictionary::TStringId g_nStringIdIX = 842;
extern const CStringDictionary::TStringId g_nStringIdIcurrent = 845;
extern const CStringDictionary::TStringId g_nStringIdIpickup_current = 854;
extern const CStringDictionary::TStringId g_nStringIdK = 870;
extern const CStringDictionary::TStringId g_nStringIdLD = 872;
extern const CStringDictionary::TStringId g_nStringIdLDO = 875;
extern const CStringDictionary::TStringId g_nStringIdLINT = 879;
extern const CStringDictionary::TStringId g_nStringIdLREAL = 884;
extern const CStringDictionary::TStringId g_nStringIdLWORD = 890;
extern const CStringDictionary::TStringId g_nStringIdMGR = 896;
extern const CStringDictionary::TStringId g_nStringIdMGR_FF = 900;
extern const CStringDictionary::TStringId g_nStringIdMGR_ID = 907;
extern const CStringDictionary::TStringId g_nStringIdOUT = 914;
extern const CStringDictionary::TStringId g_nStringIdPARAMS = 918;
extern const CStringDictionary::TStringId g_nStringIdPERMIT = 925;
extern const CStringDictionary::TStringId g_nStringIdPOLL = 932;
extern const CStringDictionary::TStringId g_nStringIdPOLL_TIME = 937;
extern const CStringDictionary::TStringId g_nStringIdPORT = 947;
extern const CStringDictionary::TStringId g_nStringIdPV = 952;
extern const CStringDictionary::TStringId g_nStringIdQ = 955;
extern const CStringDictionary::TStringId g_nStringIdQD = 957;
extern const CStringDictionary::TStringId g_nStringIdQI = 960;
extern const CStringDictionary::TStringId g_nStringIdQO = 963;
extern const CStringDictionary::TStringId g_nStringIdQU = 966;
extern const CStringDictionary::TStringId g_nStringIdQX = 969;
extern const CStringDictionary::TStringId g_nStringIdR = 972;
extern const CStringDictionary::TStringId g_nStringIdREAL = 974;
extern const CStringDictionary::TStringId g_nStringIdREQ = 979;
extern const CStringDictionary::TStringId g_nStringIdRESET = 983;
extern const CStringDictionary::TStringId g_nStringIdRESET_OUT = 989;
extern const CStringDictionary::TStringId g_nStringIdRESP = 999;
extern const CStringDictionary::TStringId g_nStringIdRMT_RES = 1004;
extern const CStringDictionary::TStringId g_nStringIdRO = 1012;
extern const CStringDictionary::TStringId g_nStringIdRQST = 1015;
extern const CStringDictionary::TStringId g_nStringIdRSP = 1020;
extern const CStringDictionary::TStringId g_nStringIdS = 1024;
extern const CStringDictionary::TStringId g_nStringIdSINT = 1026;
extern const CStringDictionary::TStringId g_nStringIdSTART = 1031;
extern const CStringDictionary::TStringId g_nStringIdSTART_TIMER = 1037;
extern const CStringDictionary::TStringId g_nStringIdSTATUS = 1049;
extern const CStringDictionary::TStringId g_nStringIdSTOP = 1056;
extern const CStringDictionary::TStringId g_nStringIdSTRING = 1061;
extern const CStringDictionary::TStringId g_nStringIdTI = 1068;
extern const CStringDictionary::TStringId g_nStringIdTIME = 1071;
extern const CStringDictionary::TStringId g_nStringIdTIME_OF_DAY = 1076;
extern const CStringDictionary::TStringId g_nStringIdTIME_UP = 1088;
extern const CStringDictionary::TStringId g_nStringIdTRIP_1 = 1096;
extern const CStringDictionary::TStringId g_nStringIdTRIP_2 = 1103;
extern const CStringDictionary::TStringId g_nStringIdTRIP_3 = 1110;
extern const CStringDictionary::TStringId g_nStringIdTRIP_4 = 1117;
extern const CStringDictionary::TStringId g_nStringIdTRIP_5 = 1124;
extern const CStringDictionary::TStringId g_nStringIdTimeOut = 1131;
extern const CStringDictionary::TStringId g_nStringIdTimeOutSocket = 1139;
extern const CStringDictionary::TStringId g_nStringIdUDINT = 1153;
extern const CStringDictionary::TStringId g_nStringIdUINT = 1159;
extern const CStringDictionary::TStringId g_nStringIdULINT = 1164;
extern const CStringDictionary::TStringId g_nStringIdUSINT = 1170;
extern const CStringDictionary::TStringId g_nStringIdVOLTAGE_A_TO_D = 1176;
extern const CStringDictionary::TStringId g_nStringIdVRMS = 1191;
extern const CStringDictionary::TStringId g_nStringIdWARM = 1196;
extern const CStringDictionary::TStringId g_nStringIdWORD = 1201;
extern const CStringDictionary::TStringId g_nStringIdWSTRING = 1206;
extern const CStringDictionary::TStringId g_nStringIdcurrent = 1214;
extern const CStringDictionary::TStringId g_nStringIdcurve_type = 1222;
extern const CStringDictionary::TStringId g_nStringIdearth_fault = 1233;
extern const CStringDictionary::TStringId g_nStringIdfault = 1245;
extern const CStringDictionary::TStringId g_nStringIdmin_trip_time = 1251;
extern const CStringDictionary::TStringId g_nStringIdovercurrent = 1265;
extern const CStringDictionary::TStringId g_nStringIdpickup_voltage = 1277;
extern const CStringDictionary::TStringId g_nStringIdtime_dial_setting = 1292;
extern const CStringDictionary::TStringId g_nStringIdtrip = 1310;
extern const CStringDictionary::TStringId g_nStringIdtrip_delay_time = 1315;
extern const CStringDictionary::TStringId g_nStringIdtrip_multiplexer = 1331;
extern const CStringDictionary::TStringId g_nStringIdtrip_time = 1348;
extern const CStringDictionary::TStringId g_nStringIdvoltage = 1358;
extern const CStringDictionary::TStringId g_nStringIdwARM = 1366;
extern const CStringDictionary::TStringId g_nStringIdNextFreeId = 1371;
extern const unsigned int cg_nNumOfConstStrings = 181;


#ifdef FORTE_STRING_DICT_FIXED_MEMORY
  CStringDictionary::TStringId CStringDictionary::scm_aunIdList[cg_unFORTE_StringDictInitialMaxNrOfStrings]
#else
  const CStringDictionary::TStringId CStringDictionary::scm_aunIdList[] 
#endif
  = {0, 8, 19, 23, 35, 43, 58, 66, 80, 88, 97, 108, 114, 124, 133, 138, 143, 152, 160, 163, 167, 173, 177, 181, 184, 189, 192, 196, 211, 214, 216, 224, 237, 249, 262, 276, 289, 304, 320, 329, 343, 356, 370, 385, 399, 415, 432, 442, 447, 461, 469, 474, 478, 481, 485, 488, 494, 497, 501, 505, 509, 517, 520, 524, 528, 532, 536, 542, 548, 555, 563, 571, 579, 586, 595, 603, 612, 621, 628, 638, 643, 654, 663, 672, 680, 685, 694, 704, 706, 717, 729, 739, 748, 760, 771, 780, 794, 797, 806, 812, 815, 819, 824, 830, 838, 842, 845, 854, 870, 872, 875, 879, 884, 890, 896, 900, 907, 914, 918, 925, 932, 937, 947, 952, 955, 957, 960, 963, 966, 969, 972, 974, 979, 983, 989, 999, 1004, 1012, 1015, 1020, 1024, 1026, 1031, 1037, 1049, 1056, 1061, 1068, 1071, 1076, 1088, 1096, 1103, 1110, 1117, 1124, 1131, 1139, 1153, 1159, 1164, 1170, 1176, 1191, 1196, 1201, 1206, 1214, 1222, 1233, 1245, 1251, 1265, 1277, 1292, 1310, 1315, 1331, 1348, 1358, 1366};

#ifdef FORTE_STRING_DICT_FIXED_MEMORY
  char CStringDictionary::scm_acConstStringBuf[cg_unFORTE_StringDictInitialStringBufSize]
#else
  const char CStringDictionary::scm_acConstStringBuf[] 
#endif
  = {"ADDRESS\0AGENT_GATE\0ANY\0ANY_ADAPTER\0ANY_BIT\0ANY_ELEMENTARY\0ANY_INT\0ANY_MAGNITUDE\0ANY_NUM\0ANY_REAL\0ANY_STRING\0ARRAY\0ARTimeOut\0ATimeOut\0BOOL\0BYTE\0CB_RESET\0CB_TRIP\0CD\0CDO\0CLEAR\0CLK\0CNF\0CO\0COLD\0CU\0CUO\0CURRENT_A_TO_D\0CV\0D\0DATA_IN\0DATA_IN_BOOL\0DATA_IN_INT\0DATA_IN_LINT\0DATA_IN_LREAL\0DATA_IN_REAL\0DATA_IN_STRING\0DATA_IN_WSTRING\0DATA_OUT\0DATA_OUT_BOOL\0DATA_OUT_INT\0DATA_OUT_LINT\0DATA_OUT_LREAL\0DATA_OUT_REAL\0DATA_OUT_STRING\0DATA_OUT_WSTRING\0DATA_TYPE\0DATE\0DATE_AND_TIME\0DEV_MGR\0DINT\0DLY\0DP\0DST\0DT\0DWORD\0EI\0EI0\0EI1\0EI2\0EMB_RES\0EO\0EO0\0EO1\0EO2\0EO3\0E_CTD\0E_CTU\0E_CTUD\0E_CYCLE\0E_DELAY\0E_DEMUX\0E_D_FF\0E_F_TRIG\0E_MERGE\0E_PERMIT\0E_RDELAY\0E_REND\0E_RESTART\0E_RS\0E_RTimeOut\0E_R_TRIG\0E_SELECT\0E_SPLIT\0E_SR\0E_SWITCH\0E_TimeOut\0G\0GEN_CLIENT\0GEN_E_DEMUX\0GEN_E_MUX\0GEN_PUBL\0GEN_PUBLISH\0GEN_SERVER\0GEN_SUBL\0GEN_SUBSCRIBE\0ID\0IED50_51\0IED64\0IN\0IND\0INIT\0INITO\0INST_ID\0INT\0IX\0Icurrent\0Ipickup_current\0K\0LD\0LDO\0LINT\0LREAL\0LWORD\0MGR\0MGR_FF\0MGR_ID\0OUT\0PARAMS\0PERMIT\0POLL\0POLL_TIME\0PORT\0PV\0Q\0QD\0QI\0QO\0QU\0QX\0R\0REAL\0REQ\0RESET\0RESET_OUT\0RESP\0RMT_RES\0RO\0RQST\0RSP\0S\0SINT\0START\0START_TIMER\0STATUS\0STOP\0STRING\0TI\0TIME\0TIME_OF_DAY\0TIME_UP\0TRIP_1\0TRIP_2\0TRIP_3\0TRIP_4\0TRIP_5\0TimeOut\0TimeOutSocket\0UDINT\0UINT\0ULINT\0USINT\0VOLTAGE_A_TO_D\0VRMS\0WARM\0WORD\0WSTRING\0current\0curve_type\0earth_fault\0fault\0min_trip_time\0overcurrent\0pickup_voltage\0time_dial_setting\0trip\0trip_delay_time\0trip_multiplexer\0trip_time\0voltage\0wARM\0"};

 
