/*******************************************************************************
 * Copyright (c) 2012 Profactor GmbH
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *   Michael Hofmann
 *     - initial API and implementation and/or initial documentation
 *******************************************************************************/

//!!!autogenerated code - DO NOT EDIT!!!
 extern const CStringDictionary::TStringId g_nStringIdBOOL;
 extern const CStringDictionary::TStringId g_nStringIdCNF;
 extern const CStringDictionary::TStringId g_nStringIdDEV_MGR;
 extern const CStringDictionary::TStringId g_nStringIdDST;
 extern const CStringDictionary::TStringId g_nStringIdID;
 extern const CStringDictionary::TStringId g_nStringIdINIT;
 extern const CStringDictionary::TStringId g_nStringIdINITO;
 extern const CStringDictionary::TStringId g_nStringIdQI;
 extern const CStringDictionary::TStringId g_nStringIdQO;
 extern const CStringDictionary::TStringId g_nStringIdREQ;
 extern const CStringDictionary::TStringId g_nStringIdRESP;
 extern const CStringDictionary::TStringId g_nStringIdRQST;
 extern const CStringDictionary::TStringId g_nStringIdSTATUS;
 extern const CStringDictionary::TStringId g_nStringIdSTRING;
 extern const CStringDictionary::TStringId g_nStringIdWSTRING;

