/*******************************************************************************
 * Copyright (c) 2012 Profactor GmbH
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *   Michael Hofmann
 *     - initial API and implementation and/or initial documentation
 *******************************************************************************/

//!!!autogenerated code - DO NOT EDIT!!!
 extern const CStringDictionary::TStringId g_nStringIdADDRESS;
 extern const CStringDictionary::TStringId g_nStringIdAGENT_GATE;
 extern const CStringDictionary::TStringId g_nStringIdBOOL;
 extern const CStringDictionary::TStringId g_nStringIdDATA_IN;
 extern const CStringDictionary::TStringId g_nStringIdDATA_IN_BOOL;
 extern const CStringDictionary::TStringId g_nStringIdDATA_IN_INT;
 extern const CStringDictionary::TStringId g_nStringIdDATA_IN_LINT;
 extern const CStringDictionary::TStringId g_nStringIdDATA_IN_LREAL;
 extern const CStringDictionary::TStringId g_nStringIdDATA_IN_REAL;
 extern const CStringDictionary::TStringId g_nStringIdDATA_IN_STRING;
 extern const CStringDictionary::TStringId g_nStringIdDATA_IN_WSTRING;
 extern const CStringDictionary::TStringId g_nStringIdDATA_OUT;
 extern const CStringDictionary::TStringId g_nStringIdDATA_OUT_BOOL;
 extern const CStringDictionary::TStringId g_nStringIdDATA_OUT_INT;
 extern const CStringDictionary::TStringId g_nStringIdDATA_OUT_LINT;
 extern const CStringDictionary::TStringId g_nStringIdDATA_OUT_LREAL;
 extern const CStringDictionary::TStringId g_nStringIdDATA_OUT_REAL;
 extern const CStringDictionary::TStringId g_nStringIdDATA_OUT_STRING;
 extern const CStringDictionary::TStringId g_nStringIdDATA_OUT_WSTRING;
 extern const CStringDictionary::TStringId g_nStringIdDATA_TYPE;
 extern const CStringDictionary::TStringId g_nStringIdDP;
 extern const CStringDictionary::TStringId g_nStringIdDT;
 extern const CStringDictionary::TStringId g_nStringIdEO;
 extern const CStringDictionary::TStringId g_nStringIdE_CYCLE;
 extern const CStringDictionary::TStringId g_nStringIdINST_ID;
 extern const CStringDictionary::TStringId g_nStringIdINT;
 extern const CStringDictionary::TStringId g_nStringIdLINT;
 extern const CStringDictionary::TStringId g_nStringIdLREAL;
 extern const CStringDictionary::TStringId g_nStringIdPOLL;
 extern const CStringDictionary::TStringId g_nStringIdPOLL_TIME;
 extern const CStringDictionary::TStringId g_nStringIdPORT;
 extern const CStringDictionary::TStringId g_nStringIdREAL;
 extern const CStringDictionary::TStringId g_nStringIdSTART;
 extern const CStringDictionary::TStringId g_nStringIdSTRING;
 extern const CStringDictionary::TStringId g_nStringIdTIME;
 extern const CStringDictionary::TStringId g_nStringIdWSTRING;

