/*******************************************************************************
 * Copyright (c) 2012 Profactor GmbH
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *   Michael Hofmann
 *     - initial API and implementation and/or initial documentation
 *******************************************************************************/

//!!!autogenerated code - DO NOT EDIT!!!
 extern const CStringDictionary::TStringId g_nStringIdBOOL;
 extern const CStringDictionary::TStringId g_nStringIdEO;
 extern const CStringDictionary::TStringId g_nStringIdE_RS;
 extern const CStringDictionary::TStringId g_nStringIdQ;
 extern const CStringDictionary::TStringId g_nStringIdR;
 extern const CStringDictionary::TStringId g_nStringIdS;

