/*******************************************************************************
 * Copyright (c) 2012 Profactor GmbH
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *   Michael Hofmann
 *     - initial API and implementation and/or initial documentation
 *******************************************************************************/

//!!!autogenerated code - DO NOT EDIT!!!
 extern const CStringDictionary::TStringId g_nStringIdBOOL;
 extern const CStringDictionary::TStringId g_nStringIdCLEAR;
 extern const CStringDictionary::TStringId g_nStringIdCNF;
 extern const CStringDictionary::TStringId g_nStringIdDT;
 extern const CStringDictionary::TStringId g_nStringIdEO;
 extern const CStringDictionary::TStringId g_nStringIdE_DELAY;
 extern const CStringDictionary::TStringId g_nStringIdIED64;
 extern const CStringDictionary::TStringId g_nStringIdINIT;
 extern const CStringDictionary::TStringId g_nStringIdINITO;
 extern const CStringDictionary::TStringId g_nStringIdREAL;
 extern const CStringDictionary::TStringId g_nStringIdREQ;
 extern const CStringDictionary::TStringId g_nStringIdRESET_OUT;
 extern const CStringDictionary::TStringId g_nStringIdSTART;
 extern const CStringDictionary::TStringId g_nStringIdSTART_TIMER;
 extern const CStringDictionary::TStringId g_nStringIdSTOP;
 extern const CStringDictionary::TStringId g_nStringIdTIME;
 extern const CStringDictionary::TStringId g_nStringIdTIME_UP;
 extern const CStringDictionary::TStringId g_nStringIdearth_fault;
 extern const CStringDictionary::TStringId g_nStringIdpickup_voltage;
 extern const CStringDictionary::TStringId g_nStringIdtrip;
 extern const CStringDictionary::TStringId g_nStringIdtrip_delay_time;
 extern const CStringDictionary::TStringId g_nStringIdvoltage;

