/*******************************************************************************
 * Copyright (c) 2012 Profactor GmbH
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * Contributors:
 *   Michael Hofmann
 *     - initial API and implementation and/or initial documentation
 *******************************************************************************/

//!!!autogenerated code - DO NOT EDIT!!!
 extern const CStringDictionary::TStringId g_nStringIdCB_RESET;
 extern const CStringDictionary::TStringId g_nStringIdCB_TRIP;
 extern const CStringDictionary::TStringId g_nStringIdINIT;
 extern const CStringDictionary::TStringId g_nStringIdINITO;
 extern const CStringDictionary::TStringId g_nStringIdRESET;
 extern const CStringDictionary::TStringId g_nStringIdTRIP_1;
 extern const CStringDictionary::TStringId g_nStringIdTRIP_2;
 extern const CStringDictionary::TStringId g_nStringIdTRIP_3;
 extern const CStringDictionary::TStringId g_nStringIdTRIP_4;
 extern const CStringDictionary::TStringId g_nStringIdTRIP_5;
 extern const CStringDictionary::TStringId g_nStringIdtrip_multiplexer;

